# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# ptrp #

POST http://localhost:8000/echo
Content-Type: application/x-www-form-urlencoded

content1=123&content2=456

###

POST http://localhost:8000/calc/sum
Content-Type: application/x-www-form-urlencoded

a=6&b=8

###

POST http://localhost:8000/user/register
Content-Type: application/json

{
  "username": "meimei",
  "nickname": "beautiful"
}

###

GET http://localhost:8000/
Accept: application/json

###

GET http://localhost:8000/user/lucien
Accept: application/json

###
